### ISSUE TITLE
Return Miles instead of KM

### ISSUE THREAD

**Issue by KidSquid1** [kovacsbalu/WazeRouteCalculator#28] opened 2018-10-11 21:16 UTC
Hello -

Is there a way to have the script return MILES instead of KM?

Thanks,

Squid

**Comment by welderwelder** [comment] 2018-10-15 06:07
multiply 0.621371192 :]

**Comment by kovacsbalu** [comment] 2018-10-15 07:05
Duplicate of #19

**Closed** 2018-11-21 08:54 UTC
