### ISSUE TITLE
Europe address_to_coords issue

### ISSUE THREAD

**Issue by eleonorapeck** [kovacsbalu/WazeRouteCalculator#38] opened 2019-03-20 11:07 UTC
Hi,
it seems to me that the 'address_to_coords' returns incorrect coordinates (I used Italian addresses). I think it depends on the 'EU' COORD_SERVERS: if I use 'SearchServer/mozi' instead of 'row-SearchServer/mozi' it seems to work correctly.
Let me know if you agree.

Thank you very much,
Eleonora

**Comment by Petro31** [comment] 2019-03-27 01:29
I can confirm this.  As well as many home assistant users.

**Comment by kovacsbalu** [comment] 2019-03-27 08:15
Hi @eleonorapeck, can you please give some example?

**Comment by eleonorapeck** [comment] 2019-03-27 13:38
Hi @kovacsbalu , you can try with the following address
'BOLANO, VIA ITALIA 66'
It returns the following (wrong) coordinates:
{'lat': 47.501262664, 'lon': 19.053106307, 'bounds': {}}

It seems it really depends on the region initial coords (that are centered in Budapest if I remember correctly) so it finds a Bulgarian address.

Thank you!

**Comment by Mariusthvdb** [comment] 2019-04-16 07:00
just to give this some more weight Ill add my +1

this used to work just fine:

```
# https://www.home-assistant.io/components/sensor.waze_travel_time/
  - platform: waze_travel_time
    name: Waze Amsterdam-Roosendaal
    origin: Amsterdam, NL
    destination: Roosendaal, NL
    region: 'EU'
```

but now results in these Waze errors:
```
2019-04-15 23:19:44 ERROR (SyncWorker_18) [homeassistant.components.waze_travel_time.sensor] Error on retrieving data: Cannot get coords for Amsterdam, NL
2019-04-15 23:24:46 ERROR (SyncWorker_1) [homeassistant.components.waze_travel_time.sensor] Error on retrieving data: Cannot get coords for Amsterdam, NL
2019-04-15 23:34:47 ERROR (SyncWorker_15) [homeassistant.components.waze_travel_time.sensor] Error on retrieving data: Cannot get coords for Amsterdam, NL
2019-04-15 23:44:54 ERROR (SyncWorker_6) [homeassistant.components.waze_travel_time.sensor] Error on retrieving data: Cannot get coords for Amsterdam, NL
```

please see if you can return the functionality

**Comment by kovacsbalu** [comment] 2019-04-16 07:41
@Mariusthvdb try with full name: 
```
From: Amsterdam, Netherlands - to: Roosendaal, Netherlands
Time 54.45 minutes, distance 69.70 km.
```

**Comment by kovacsbalu** [comment] 2019-04-16 08:08
@eleonorapeck you can fix with adding country. Try this: 
```
From: Italy, Bolano, Via Italia 66 - to: Italy, La Spezia, Porto Mirabello
{'lat': 44.163387298583984, 'lon': 9.88122272491455, 'bounds': {}}
{'lat': 44.10076141357422, 'lon': 9.82806396484375, 'bounds': {}}
Time 21.57 minutes, distance 10.45 km.
```

**Comment by kovacsbalu** [comment] 2019-04-16 08:15
WazeRouteCalculatro use address to coord like waze.com/editor. Maybe neeed to check live maps solution.

**Comment by Mariusthvdb** [comment] 2019-04-18 20:10
@kovacsbalu 
thanks. 
Just noticed that my Homeassistant instance 84.3 reads the Waze_travel_time coordinates perfectly fine...

it's my HA 91.2 set-up causing the issues. So either the component in HA has changed something incorrectly or the full updated caused things to go awol
Maybe @petro31 knows more about this?

have a look:

HA 84.3
![Schermafbeelding 2019-04-18 om 22 07 51](https://user-images.githubusercontent.com/33354141/56388102-7011ba00-6226-11e9-9536-70c44ed2acc9.jpg)

and HA 91.2:

![Schermafbeelding 2019-04-18 om 22 08 37](https://user-images.githubusercontent.com/33354141/56388158-8e77b580-6226-11e9-9741-f8e166c9dc2a.jpg)


with the exact same setup, as provided a few post above.

**Comment by Petro31** [comment] 2019-05-16 17:44
Nothing can be done.  I put in a PR against home assistant back in march and it hasn't been merged.  You're welcome to use it as a custom component.  You can also just use the 84.3 version as a custom component.  Either way, my hands are tied in the matter.

**Comment by hmmbob** [comment] 2019-05-16 20:55
The Home Assistent pull request has the "in progress" label still attached to it (probably falsely). Items with "in progress" are filtered when the developers select PRs for the updates - hence your PR was likely never seen.

It also has some branch issues by now - maybe solve those to get the label removed, and/or try opening a new PR (again .....).



(I'm no dev, just noting my observations)

**Comment by Petro31** [comment] 2019-05-16 23:01
Ah, I did not know that.  I only dev for them once and a while.  Partly because of issues like this.  I'll see if I can remove the in process flag and clear the merge issues.  They are minor and i'm not even sure why they are coming up as none of the files cross with the recent changes.  Probably some safety precaution.

**Comment by Mariusthvdb** [comment] 2019-06-28 13:43
> @Mariusthvdb try with full name:
> 
> ```
> From: Amsterdam, Netherlands - to: Roosendaal, Netherlands
> Time 54.45 minutes, distance 69.70 km.
> ```
> 
> BTW you should check addresses on https://www.waze.com/livemap

sorry I forgot to get back on this...

I did change to the full names, and indeed it returns a distance now, but it completely incorrect.. Which is rather awkward since there are no other cities with the same name....

tried it in Dutch (as the website does) but that is not recognized...

All in all, it is a pity we can't simply calculate the travel time between 2 cities (by name) ,( or a city and a device or gs coordinate for that matter), directly.

would this be enhanced in the near future?

**Comment by CrispinP** [comment] 2019-06-30 21:49
I've just started seeing these errors too.
I have 3 checks - it seems that the UK post codes are having a problem being found. From my house to W14 9YW is apparently 197km. It's only around 30. To another postcode, SW1X 7XL, it complains it cannot find the coords for it.

Has waze changed something that is causing this?

**Comment by kovacsbalu** [comment] 2019-07-11 06:51
Hi @CrispinP, can you please show and example? Please try to check your addresses on waze live map.

**Comment by CrispinP** [comment] 2019-07-19 22:02
@kovacsbalu 
Postal address on the live map works but Waze converts / suggests a slightly better address; it prefixes it with London.
If I put the full address in then it works ok.

I don't think this is your error or anything you can change. In the UK post codes are pretty exact and it should work. Waze is decoding the address wrong.


Solution: Put the full address in and it works :)

Thank you for the tool 👍

**Comment by CrispinP** [comment] 2019-07-19 22:14
ok, scratch that. There is something funky going on. The exact address, no matter what I use, is landing somewhere odd. See screen grab below
![image](https://user-images.githubusercontent.com/27884877/61568223-4f9e0980-aa7a-11e9-8589-91cac188e664.png)


Here is what google thinks: https://www.google.co.uk/maps/dir/SG14+1PB/W14+9YW/@51.6445848,-0.3667965,11z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0x48762692f12f5a4f:0xdcfad6fbbd03a083!2m2!1d-0.07319!2d51.7979558!1m5!1m1!1s0x48760fc1cc1442a3:0xde8b517811c6590a!2m2!1d-0.212513!2d51.4967339

Very odd.

**Comment by kovacsbalu** [comment] 2019-07-22 07:08
@CrispinP check this:

```
From: SG14 1PB, Bluecoats Ave, Hertford, UK - to: W14 9YW, Hammersmith, London, UK
Time 81.48 minutes, distance 47.80 km.
```

```
From: SG14 1PB - to: W14 9YW
Time 164.23 minutes, distance 188.32 km.
```

**Comment by CrispinP** [comment] 2019-07-22 08:46
I wonder why they no longer resolve the postcode to an exact address. Moreso, I wonder to where this postcode is resolved.

I guess this is not your problem or anything you can control.

thanks for the time and effort.


C

**Closed** 2019-10-12 20:39 UTC
