### ISSUE TITLE
Issue with coordinates in australia

### ISSUE THREAD

**Issue by lichessboy** [kovacsbalu/WazeRouteCalculator#76] opened 2023-08-20 04:58 UTC
I have an issue with australian travel times
i have the riegon as 'AU' so that may be the issue

Output
From: 1 Marita Road, Perth, WA - to: 1 North Street, Perth, WA Start coords: (-34.4881591796875, 150.90646362304688) End coords: (-31.931893945, 115.85721939) Time 2661.83 minutes, distance 4010.51 km.
this is incorrect because 1 northstreet is like 1KM from Marita Road so it makes no sense

Output
From: 1 Marita Road, Perth, WA - to: 5 Davies Road, Perth, WA Start coords: (-34.4881591796875, 150.90646362304688) End coords: (-34.4881591796875, 150.90646362304688) Time 0.23 minutes, distance 0.04 km.
this is actually correct,

Output
From: 182 Little Marine Parade, Perth, WA - to: 5 Davies Road, Perth, WA Start coords: (-27.988226795, 153.429991207) End coords: (-34.4881591796875, 150.90646362304688) Time 581.32 minutes, distance 952.95 km.

but this is also incorrect, as these places are also 5KM from each other, so i dont think the start coords are correct, cos 153 isnt the y coord of 182 Little Marine Parade.

how do i fix this issue, it seems like it is just getting the wrong place, is there anyway to ensure that this doesnt happen?
specifying the suburb ect. could potentially be done, but the suburbs are just randomly assigned in my data, with many of them just being 'suburb1', so if there are any other suggestions that would be easier as i have hundreds of addresses in my db.

**Comment by kovacsbalu** [comment] 2023-08-21 07:16
Duplicate of #60

**Closed by kovacsbalu** 2023-08-21 07:16 UTC
